version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 21 # 3 weeks

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    cooldown:
      # 48h due to being highly trusted sources
      default-days: 2
