name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - env:
          # ruleid: secrets-without-environment-in-env-block
          foo: ${{ secrets.PROD_API_KEY }}
        run: |
          echo "$foo"
---
name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          foo1: bar
          # ruleid: secrets-without-environment-in-env-block
          foo: "${{ secrets.PROD_API_KEY }}"
          foo2: bar
        run: |
          echo "$foo"
---
name: CI

on:
  push:
    branches: [main]

# Test surrounded by other jobs
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: do something
        env:
          # ruleid: secrets-without-environment-in-env-block
          foo: ${{ secrets.PROD_API_KEY }}
        run: |
          echo "$foo"
  finalize:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
---
name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        # Shouldn't match when using GITHUB_TOKEN
        # ok: secrets-without-environment-in-env-block
        run: echo "${{ secrets.GITHUB_TOKEN }}"
---
name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: my-env
    steps:
      - if: ${{ true }}
        env:
          # Shouldn't match when an environment is used
          # ok: secrets-without-environment-in-with-block
          foo: ${{ secrets.PROD_API_KEY }}
---
name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # Should match when passing a secret to 'with' block
          # ruleid: secrets-without-environment-in-with-block
          token: ${{ secrets.MY_TOKEN }}
---
name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        # Test with quoted secret + surrounded by other keys
        with:
          foo1: bar
          # ruleid: secrets-without-environment-in-with-block
          token: "${{ secrets.MY_TOKEN }}"
          foo2: bar
---
name: CI

on:
  push:
    branches: [main]

# Test surrounded by other jobs
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # ruleid: secrets-without-environment-in-with-block
          token: "${{ secrets.MY_TOKEN }}"
  finalize:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
---
name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # Shouldn't match when using GITHUB_TOKEN
          # ok: secrets-without-environment-in-with-block
          token: ${{ secrets.GITHUB_TOKEN }}
---
name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: my-env
    steps:
      - if: ${{ true }}
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # Shouldn't match when an environment is used
          # ok: secrets-without-environment-in-with-block
          token: ${{ secrets.PROD_API_KEY }}
---
name: CI

on:
  push:
    branches: [main]

jobs:
  reusable-workflow:
    uses: saleor/foo
    with:
      # Environments aren't supported in reusable workflows
      # as per https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows
      # ok: secrets-without-environment-in-with-block
      token: ${{ secrets.PROD_API_KEY }}
