name: Semgrep CI
on:
  workflow_call:
    inputs:
      check_name:
        type: string
        default: ""
        description: |
          The name of the check, defaults the tool name from the SARIF file
          (usually "Semgrep OSS").
          `check_name` should be set to a different name if there are multiple
          Semgrep workflows running inside the same pull request.

      configs:
        required: false
        type: string
        description: |
          Whitespace or newline separated semgrep YAML configuration paths or URLs, e.g.:
          - auto
          - p/python (public library)
          - ./rules/my-rule.yaml (single YAML file)
          - ./my-rules/ (directory of N YAML files)

          By default the rules will be added on top of this workflow's default rules
          (see the input `use_default_config` and the environment variable
          `DEFAULT_CONFIG` for more information).

      use_default_config:
        type: boolean
        default: true
        description: |
          If 'false' then only the rules defined in `inputs.configs` will be ran
          instead of both `inputs.configs` and `DEFAULT_CONFIG`.

      exclude_rules:
        required: false
        type: string
        description: Rule IDs to skip.

      use_default_exclude_rules:
        type: boolean
        default: true
        description: |
          If 'false' then only the rule IDs defined in `inputs.exclude_rules` will be
          excluded instead of also excluding the contents from `DEFAULT_EXCLUDE_RULE_IDS`.

env:
  SARIF_OUTPUT_FILE: semgrep-results.sarif
  SARIF_ARTIFACT_NAME: Semgrep OSS SARIF Results
  # The semgrep rules to run unless `inputs.use_default_config == false`.
  DEFAULT_CONFIG: |
    auto
    p/ci
    r/yaml.github-actions
    ./saleor-rules/yaml
    ./saleor-rules/typescript
  # yaml.github-actions.[...].run-shell-injection is duplicate of saleor-rules.yaml.github-actions.script-injection
  DEFAULT_EXCLUDE_RULE_IDS: |
    yaml.github-actions.security.run-shell-injection.run-shell-injection

permissions:
  contents: read

jobs:
  scan:
    name: semgrep/ci
    runs-on: ubuntu-24.04
    container:
      # Note: the non-root flavor doesn't work on GHA (e.g., 1.57.0-nonroot).
      image: returntocorp/semgrep:1.153.1@sha256:50b839b576d76426efd3e5cffda2db0d8c403f53aa76e91d42ccf51485ac336c

    steps:
      # Clone the invoker's repository.
      - if: ${{ !env.ACT }}
        name: Checkout Caller's Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Clone the custom semgrep rules (this GitHub repository).
      - if: ${{ !env.ACT }}
        name: Checkout Custom Semgrep Rules
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Unfortunately we cannot detect the GitHub repository, and git ref of
          # the invoked workflow (this file) in pull requests due to not having access
          # to id_token permission thus the Git repository needs to be hard-coded
          # and always use `main` branch.
          # Feature request: https://github.com/orgs/community/discussions/31054
          repository: saleor/semgrep-rules
          ref: main
          # Note: the directory name will be used for rule IDs
          # (e.g., saleor-rules.typescript.my-check).
          # Thus avoid changing the path and ensure the name is meaningful.
          path: ./saleor-rules
          set-safe-directory: false

      - name: Run Semgrep Rules
        shell: bash
        env:
          TARGETS: ${{ inputs.targets }}
          CONFIG_PATHS: ${{ inputs.configs }}
          USE_DEFAULT_CONFIG: ${{ inputs.use_default_config }}
          USE_DEFAULT_EXCLUDE_RULES: ${{ inputs.use_default_exclude_rules }}
          EXCLUDE_RULES: ${{ inputs.exclude_rules }}
        run: |
          set -u -o pipefail

          cmd_args=(
              # Do not check for version update as we are inside a CI.
              "--disable-version-check"
              # Save the results into a SARIF file to add them as PR annotations.
              "--output=$SARIF_OUTPUT_FILE"
              "--sarif"
              # Disable .gitignore in favor of using .semgrepignore to prevent
              # 'git add --force' from being silently ignored, thus forcing
              # the users to be explicit.
              "--no-git-ignore"
          )

          # Add extra logging if the runner was run with debug logging.
          test -z "${RUNNER_DEBUG+x}" || cmd_args+=( "--verbose" )

          if [ "$USE_DEFAULT_CONFIG" == true ]; then
            CONFIG_PATHS="$DEFAULT_CONFIG $CONFIG_PATHS"
          fi

          if [ "$USE_DEFAULT_EXCLUDE_RULES" == true ]; then
            EXCLUDE_RULES="$DEFAULT_EXCLUDE_RULE_IDS $EXCLUDE_RULES"
          fi

          # Gather the config input whitespace-separate value
          # into a list of `--config=<value>` arguments.
          read -d '' -r -a configs < <(echo "$CONFIG_PATHS") || true
          for cfg in "${configs[@]}"; do
            cmd_args+=( "--config=$cfg" )
          done

          # Gather the excluded rules ID into a list
          # of `--exclude-rule=<value>` arguments.
          read -d '' -r -a exclude_rules < <(echo "$EXCLUDE_RULES") || true
          for excluded_rule_id in "${exclude_rules[@]}"; do
            cmd_args+=( "--exclude-rule=$excluded_rule_id" )
          done

          semgrep ci "${cmd_args[@]}"

      - uses: saleor/sarif-to-annotations@feat/add-action
        name: Export SARIF Results
        # Always export the SARIF results file (if it exists) as semgrep
        # checks will fail on blocking errors, but we still want to display them
        # as PR annotations.
        if: ${{ always() }}
        with:
          sarif-file: ${{ env.SARIF_OUTPUT_FILE }}

      # Allow to download the results for local analysis
      - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # 4.3.0
        name: Export SARIF Results
        if: ${{ always() }}
        with:
          name: ${{ env.SARIF_ARTIFACT_NAME }}
          path: ${{ env.SARIF_OUTPUT_FILE }}
          if-no-files-found: error
          retention-days: 1
