name: Test Semgrep Rules
on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Checks for syntax errors and runs 'p/semgrep-rule-lints'.
      - name: Validate Rules
        shell: bash
        run: make validate

      - name: Test Rules
        run: make test

      # This runs the rules from https://github.com/semgrep/semgrep-rules/tree/835867f89e4ba07f8bb4a6a1619507408e63e9b0/yaml/semgrep
      # to ensure best practices are followed. The CI will only fail on error.
      - name: Run Semgrep Rules Recommendation Checks
        run: make checks
